apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config-urs
  namespace: default
data:
  NEW_FEATURE: "true"

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spinnaker-demo-urs
  namespace: default
  labels:
    source: demo-urs
    stack: frontend-urs
    app: spinnaker-urs
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo-urs
      app: spinnaker-urs
  template:
    metadata:
      labels:
        source: demo-urs
        app: spinnaker-urs
    spec:
      containers:
      - name: primary
        image: index.docker.io/lwander/spin-kub-v2-demo
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config-urs

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo-urs
  namespace: default
spec:
  selector:
    source: demo-urs
    app: spinnaker-urs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
